AWSTemplateFormatVersion: '2010-09-09'
Description: Set up an AWS CodePipeline to deploy a FastAPI application to ECS using Fargate.

Parameters:
  GitHubToken:
    Type: String
    NoEcho: true
    Description: Personal Access Token for GitHub
  GitHubRepoOwner:
    Type: String
    Description: GitHub repository owner
  GitHubRepoName:
    Type: String
    Description: GitHub repository name
  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub branch to use

Resources:

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:*
                  - logs:*
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: CodeBuildFastAPIBuild
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/${GitHubRepoOwner}/${GitHubRepoName}
        GitCloneDepth: 1
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: us-east-1
          - Name: IMAGE_REPO_NAME
            Value: fastapi-app
          - Name: AWS_ACCOUNT_ID
            Value: 021891608005
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: NO_CACHE

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - codebuild:*
                  - ecs:*
                  - iam:PassRole
                Resource: "*"

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: CodePipelineFastAPIPipeline
      RoleArn: !GetAtt PipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: !Ref GitHubRepoOwner
                Repo: !Ref GitHubRepoName
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
        - Name: Approval
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              Configuration: {}
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: 1
              Configuration:
                ClusterName: !Ref ECSCluster
                ServiceName: !Ref Service
                FileName: imagedefinitions.json
              InputArtifacts:
                - Name: BuildOutput
      ArtifactStore:
        Type: S3
        Location: !Sub "${AWS::AccountId}-codepipeline-artifacts"

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: FastAPIClusterTest

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: FastAPITaskDefinition
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: FastAPIContainer
          Image: "021891608005.dkr.ecr.us-east-1.amazonaws.com/fastapi-app:latest"
          PortMappings:
            - ContainerPort: 8000
              Protocol: tcp

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: 
            - subnet-0dce05ec0214f4ec5 # Replace with actual subnet IDs
          SecurityGroups:
            - sg-0af3d880ed68f2d31 # Replace with actual security group IDs
          AssignPublicIp: ENABLED

  PipelineNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: CodePipelineNotifications

  PipelineNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref PipelineNotificationTopic
      Endpoint: "kanishcloud@gmail.com " # Replace with your email

Outputs:
  PipelineName:
    Description: The name of the CodePipeline
    Value: !Ref CodePipeline
